"""Reliax: per-decision reliability envelopes for AI systems.

This is a placeholder release that reserves the package name. The client SDK
is in development; see https://github.com/reliax-io/reliax-python for status.

What Reliax does
----------------
Reliax sits beside a model, never inside it, and assesses each prediction at
inference time. Every decision carries:

- a conformal prediction set with a coverage guarantee at a declared level,
  marginally and on each declared segment,
- a credibility p-value answering whether the input is exchangeable with the
  calibration data,
- a Venn-Abers calibrated risk bracket,
- an anytime-valid drift verdict from a test martingale on inputs and scores,
- a routing verdict (allow, review or block) under a versioned policy,
- a hash-chained audit record an auditor can replay.

No model weights and no training data are required.

What is guaranteed and what is not
----------------------------------
Three components are theorems and routing runs on them: conformal coverage,
Venn-Abers calibration, and the anytime-valid drift martingale. Two are
signals and are labelled as such: the triage rank and the calibration
opinion. Signals never enter a routing rule.

Coverage is a property of the procedure over exchangeable data, not a
probability attached to any single prediction. Per-instance conditional
coverage is provably unattainable distribution-free.

Evidence
--------
Measured results on public credit data, including the negative ones, are at
https://github.com/reliax-io/reliax-evaluation. Every published number is
regenerated by a runner script in that repository.

License
-------
Apache-2.0. The reliability engine is licensed separately; see
https://reliax.io.
"""

__version__ = "0.0.1"

__all__ = ["__version__"]
